DTO-HW
YevheniiVlasenko/Spring-Boot-Intro pull request #1
Opened 2023-12-06 19:20 UTC by YevheniiVlasenko

2023-12-07 10:29 UTC, ponomvrenko requested changes

2023-12-07 10:29 UTC, ponomvrenko commented on src/main/java/project/bookstore/controller/BookController.java
> +
You already use this annotation before, so it will be good to use it here too `@RequiredArgsConstructor`

2023-12-07 10:29 UTC, ponomvrenko commented on src/main/java/project/bookstore/repository/BookRepository.java
> +    Book getById(Long id);
Imagine, that we are looking for a book by incorrect ID... Should we return null?

2023-12-07 15:29 UTC, vovasalyha requested changes
Looks good, but review your logic with use of Optional when fetching entity by ID.

2023-12-07 15:29 UTC, vovasalyha commented on src/main/java/project/bookstore/repository/BookRepository.java
> +    Book getById(Long id);
It's better to return Optional from this method.

2023-12-07 15:29 UTC, vovasalyha commented on src/main/java/project/bookstore/controller/BookController.java
> +        return Optional.of(bookService.getBookById(id))
It's better to return Optional from the repository and throw an exception from service if entity is not found.

2023-12-07 16:03 UTC, YevheniiVlasenko commented on src/main/java/project/bookstore/controller/BookController.java
> +        return Optional.of(bookService.getBookById(id))
Ok, but shouldn't we catch exceptions as soon as possible?

2023-12-07 16:07 UTC, vovasalyha commented on src/main/java/project/bookstore/controller/BookController.java
> +        return Optional.of(bookService.getBookById(id))
But a service handles response from repository first, only after that it goes back to the controller :) So by your logic, service should check and throw an exception.

2023-12-08 10:09 UTC, d1sam requested changes
Well done, but some changes with optional should be done. Mistake with optional marked by mentors earlier still exists.

2023-12-08 10:09 UTC, d1sam commented on src/main/java/project/bookstore/model/Book.java
> +
```suggestion

```

2023-12-08 10:09 UTC, d1sam commented on src/main/java/project/bookstore/repository/BookRepository.java
> +    Optional<Book> getById(Long id);
```suggestion
    Optional<Book> findById(Long id);
```

2023-12-08 10:09 UTC, d1sam commented on src/main/java/project/bookstore/repository/BookRepositoryImpl.java
> +            return Optional.of((Book) query.getSingleResult());
```suggestion
            return Optional.ofNullable(entityManager.find(Book.class, id));
```
you can simplify your logic :)

2023-12-08 10:09 UTC, d1sam commented on src/main/java/project/bookstore/controller/BookController.java
> +                        .orElseThrow(() -> new EntityNotFoundException(FIND_BY_ID_MSG + id));
```suggestion
        return bookService.getBookById(id);
```
you already check optional in your service layer. You don't need to do this on controller layer.

2023-12-11 16:50 UTC, merged