Data jpa
YevheniiVlasenko/Spring-Boot-Intro pull request #2
Opened 2023-12-12 17:35 UTC by YevheniiVlasenko

2023-12-12 18:40 UTC, AgroFix approved these changes

2023-12-12 18:40 UTC, AgroFix commented on src/main/resources/application.properties
>  spring.datasource.password=715914qQ()
I hope this is not your real password😏

2023-12-12 18:40 UTC, AgroFix commented on src/main/java/project/bookstore/service/BookService.java
> +    Book update(Long id, CreateBookRequestDto createBookRequestDto);
why Book, but not BookDto

2023-12-13 07:09 UTC, kshuryhin requested changes
Good job, but there are some points to consider

2023-12-13 07:09 UTC, kshuryhin commented on src/main/java/project/bookstore/service/BookServiceImpl.java
> +    public void safeDelete(Long id) {
I guess more general method name, like `delete` will be preferable here. In my opinion, if in the future you would like to change safe delete on real one, those implementation details will not affect more abstract service method name. But that is minor point

2023-12-13 07:09 UTC, kshuryhin commented on src/main/java/project/bookstore/service/BookService.java
> +    Book update(Long id, CreateBookRequestDto createBookRequestDto);
It looks like we should operate with DTOs on the service layer

2023-12-13 07:09 UTC, kshuryhin commented on src/main/java/project/bookstore/model/Book.java
> +@Where(clause = "is_deleted=false")
'org.hibernate.annotations.Where' is deprecated

2023-12-13 08:58 UTC, YevheniiVlasenko commented on src/main/resources/application.properties
>  spring.datasource.password=715914qQ()
just another mock data)

2023-12-13 10:18 UTC, YevheniiVlasenko commented on src/main/java/project/bookstore/model/Book.java
> +@Where(clause = "is_deleted=false")
It is, but it's used in the lesson video

2023-12-13 15:36 UTC, vovasalyha approved these changes
LGTM

2023-12-13 16:07 UTC, merged