Security
YevheniiVlasenko/Spring-Boot-Intro pull request #6
Opened 2023-12-25 15:16 UTC by YevheniiVlasenko

2023-12-26 07:07 UTC, ponomvrenko requested changes

2023-12-26 07:07 UTC, ponomvrenko commented on src/main/java/project/bookstore/model/Role.java
> +    private String name;
We've already created enum with our names, so you should replace String type

2023-12-26 07:07 UTC, ponomvrenko commented on src/main/java/project/bookstore/model/User.java
> +    @Column(nullable = false)
Define here a name for column

2023-12-26 08:11 UTC, d1sam requested changes
Good job, but some changes should be done according to my comment

2023-12-26 08:11 UTC, d1sam commented on hs_err_pid11760.log
what is a file?

2023-12-26 08:11 UTC, d1sam commented on src/main/java/project/bookstore/controller/BookController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
```suggestion
    @PreAuthorize("hasAnyAuthority('ROLE_USER', 'ROLE_ADMIN')")
```

2023-12-26 08:11 UTC, d1sam commented on src/main/java/project/bookstore/controller/BookController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
```suggestion
    @PreAuthorize("hasAnyAuthority('ROLE_USER', 'ROLE_ADMIN')")
```

2023-12-26 08:11 UTC, d1sam commented on src/main/java/project/bookstore/model/Role.java
> +    private String name;
```suggestion
    private RoleName name;
```

2023-12-26 08:11 UTC, d1sam commented on src/main/java/project/bookstore/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-12-26 08:11 UTC, d1sam commented on src/main/java/project/bookstore/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-12-26 08:11 UTC, d1sam commented on src/main/java/project/bookstore/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-12-26 08:11 UTC, d1sam commented on src/main/java/project/bookstore/repository/RoleRepository.java
> +
```suggestion
@Repository
```

2023-12-26 08:11 UTC, d1sam commented on src/main/java/project/bookstore/security/SecurityConfig.java
> +                                        "/swagger-resources/**").permitAll()
```suggestion
                                .requestMatchers("/auth/**", "/swagger-ui/**", "/v3/api-docs/**").permitAll()
```

2023-12-26 08:11 UTC, d1sam commented on src/main/resources/db/changelog/changes/03-create-roles-table.yaml
> +                    nullable: false
Please add empty line to the end of file

2023-12-26 08:11 UTC, d1sam commented on src/main/resources/db/changelog/changes/04-create-users-roles-table.yaml
> +                    references: roles(id)
Please add empty line to the end of file

2023-12-26 08:11 UTC, d1sam commented on src/main/resources/db/changelog/changes/05-insert-admin-user-to-db.yaml
> +                  value: qwerty
password not hashed

2023-12-26 08:11 UTC, d1sam commented on src/main/resources/db/changelog/changes/06-add-customer-user-to-db.yaml
> +                  value: qwerty
password not hashed

2023-12-26 08:11 UTC, d1sam commented on src/main/resources/db/changelog/changes/08-add-roles-to-roles-table.yaml
> +
only 1 empty line should be at the end of file

2023-12-26 08:11 UTC, d1sam commented on src/main/resources/db/changelog/changes/06-add-customer-user-to-db.yaml
> +                  value: qwerty
I see you hash password in the next changesets, but please be careful with passwords inside your changesets

2023-12-26 08:11 UTC, d1sam commented on src/main/resources/db/changelog/changes/05-insert-admin-user-to-db.yaml
> +                  value: qwerty
I see you hash password in the next changesets, but please be careful with passwords inside your changesets

2023-12-26 08:11 UTC, d1sam commented on src/main/resources/db/changelog/changes/09-add-role-column-to-user-table.yaml
> +                  type: VARCHAR(255)
please add empty line to the end of file

2023-12-26 08:11 UTC, d1sam commented on src/main/resources/db/changelog/changes/09-add-role-column-to-user-table.yaml
> +                  type: VARCHAR(255)
why do you need this column? you already have `users_roles` table

2023-12-26 17:10 UTC, yevheniisynytsia requested changes

2023-12-26 17:10 UTC, yevheniisynytsia commented on hs_err_pid11760.log
> +#
can you remove this file?

2023-12-27 08:06 UTC, d1sam requested changes
good job, but some changes in your migration files should be done.

2023-12-27 08:06 UTC, d1sam commented on src/main/resources/db/changelog/changes/04-create-users-roles-table.yaml
You should add **composite** [key](https://www.simplilearn.com/tutorials/sql-tutorial/composite-key-in-sql#:~:text=View%20More-,What%20Is%20a%20Composite%20Key%20in%20SQL%3F,can%20uniquely%20identify%20any%20record.)

2023-12-27 08:06 UTC, d1sam commented on src/main/resources/db/changelog/changes/10-assign-roles-to-existing-users.yaml
try to improve your code and use `valueComputed` with `preConditions` for your insert.
Example:
```
      preConditions:
        - sqlCheck:
            expectedResult: 1
            sql: SELECT COUNT(*) FROM users WHERE email='admin@example.com'
        - sqlCheck:
            expectedResult: 1
            sql: SELECT COUNT(*) FROM roles WHERE name='ROLE_ADMIN'
      changes:
        - insert:
            tableName: user_role
            columns:
              - column:
                  name: user_id
                  valueComputed: (SELECT id FROM users WHERE email='admin@example.com')
              - column:
                  name: role_id
                  valueComputed: (SELECT id FROM roles WHERE name='ROLE_ADMIN')
```

2023-12-27 08:12 UTC, YevheniiVlasenko commented on src/main/resources/db/changelog/changes/10-assign-roles-to-existing-users.yaml
Isn't it just the same action with a lot of complications in this particular case?

2023-12-27 11:41 UTC, d1sam approved these changes
Well done!

2023-12-27 11:41 UTC, d1sam commented on src/main/resources/db/changelog/changes/10-add-primary-key-for-users-roles.yaml
> +            tableName: users_roles
```suggestion
            tableName: users_roles
            
```

2023-12-27 11:46 UTC, merged