Jwt
YevheniiVlasenko/Spring-Boot-Intro pull request #7
Opened 2023-12-27 11:57 UTC by YevheniiVlasenko

2023-12-27 15:45 UTC, vovasalyha requested changes
Looks good, but see a couple of comments. Also, resolve all merge conflicts.

2023-12-27 15:45 UTC, vovasalyha commented on src/main/java/project/bookstore/dto/user/UserLoginRequestDto.java
> +    @NotEmpty
What if I pass `" "`? Also, validate the minimum and maximum size, to not exceed DB constraints.

2023-12-27 15:45 UTC, vovasalyha commented on src/main/java/project/bookstore/controller/AuthenticationController.java
> +    public UserLoginResponseDto login(@RequestBody UserLoginRequestDto requestDto) {
@Valid

2023-12-27 15:45 UTC, vovasalyha commented on src/main/java/project/bookstore/controller/AuthenticationController.java
>      public UserResponseDto register(@RequestBody UserRegistrationRequestDto request)
@Valid

2023-12-27 15:45 UTC, vovasalyha commented on src/main/java/project/bookstore/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Make `"Bearer "` a constant. You can then use this constant `length()` instead of TOKEN_START_INDEX

2023-12-27 15:45 UTC, vovasalyha commented on src/main/java/project/bookstore/security/JwtUtil.java
> +    public boolean isValidToken(String token) {
```suggestion
    public boolean isTokenValid(String token) {
```

2023-12-27 16:27 UTC, YevheniiVlasenko commented on src/main/java/project/bookstore/dto/user/UserLoginRequestDto.java
> +    @NotEmpty
Doesn't the @Email annotation cover this case?

2023-12-28 11:00 UTC, bhdnchui requested changes
Just a few points to consider.
Also, fix checkstyle errors.

2023-12-28 11:00 UTC, bhdnchui commented on src/main/java/project/bookstore/dto/user/UserLoginRequestDto.java
> +    @NotEmpty
Please, investigate the difference between `@NotEmpty` and `@NotBlank`.
Add max size validation.

2023-12-28 11:00 UTC, bhdnchui commented on src/main/java/project/bookstore/controller/AuthenticationController.java
> +    public UserResponseDto register(@RequestBody UserRegistrationRequestDto request) {
Why did you change it? 
Think about throwing a narrower exception [here](https://github.com/YevheniiVlasenko/Spring-Boot-Intro/blob/main/src/main/java/project/bookstore/service/UserServiceImpl.java#L21).
`@Valid`

2023-12-28 13:51 UTC, d1sam approved these changes
well done, but please avoid String literals and instead use constants :)

2023-12-28 13:51 UTC, d1sam commented on src/main/java/project/bookstore/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
try to avoid string literals, instead use constants.

2023-12-28 15:49 UTC, merged